# Generated by Django 4.2.17 on 2025-02-01 13:28

import ansible_base.oauth2_provider.models.access_token
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_oauth2_provider', '0007_alter_oauth2accesstoken_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='scope',
            field=models.CharField(default='write', help_text="Allowed scopes, further restricts user permissions. Must be a simple space-separated string with allowed scopes ['read', 'write'].", max_length=256, validators=[ansible_base.oauth2_provider.models.access_token.validate_scope]),
        ),
    ]
